
avatar: /images/avatar.gif

menu:
  archives:
    url: /archives
    icon: '&#xe61b;'
  tags:
    url: /tags
    icon: '&#xe601;'
  gallery:
    url: /gallery
    icon: '&#xe7be;'
  links:
    url: /links
    icon: '&#xe600;'
  about:
    url: /about
    icon: '&#xe61e;'

social:
  Github:
    url: https://github.com/JeanwayHwang
    icon: '&#xe8ef;'
  QQ:
    url: tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=337677313
    icon: '&#xe602;'
  Mail:
    url: mailto:337677313@qq.com
    icon: '&#xe959;'

excerpt_length: 100

links:
  StaunchKai: 
    img: http://pqpwr348b.bkt.clouddn.com/staunch.gif
    url: https://staunchkai.com

favicon: /images/favicon.ico

# Valine评论系统 & LeanCloud平台的应用Key
Valine:
  api_id: 'wtJpPCFTapMP0bD2NRIJTS4m-gzGzoHsz'
  api_key: 'pl9EsSB2Q3cAn2qi834I12tJ'
  placeholder: '谈天说地'

reward:
  # 0-关闭, 1-所有文章均有打赏, 2-文章的md文件里有reward:true属性，才有打赏
  status: 1
  # 标题
  title: 感谢认可，么么哒！
  # 微信，关闭设为 false
  wechat: images/wxpay_code.jpg
  # 支付宝，关闭设为 false
  alipay: images/alipay_code.jpg

copyright: '© 2019 JeanwayHwang All Rights Reserved'
icp: ''